image: python:3
lint:
  stage: build
  script:
    - pip install yapf==0.32.0
    - yapf --style google --recursive .
  only:
    - pushes
unittest:
  stage: test
  dependencies:
    - pipeline: test
      job: lint
  script:
    - pip install -r requirements.txt
  only:
    - pushes